export const EMP_CHANGE_NAME = 'EMP_CHANGE_NAME';
export const EMP_CHANGE_AGE = 'EMP_CHANGE_AGE';
export const FETCH_LEAGUES = 'FETCH_LEAGUES';
export const FETCH_LEAGUES_PENDING = 'FETCH_LEAGUES_PENDING';
export const FETCH_LEAGUES_REJECTED = 'FETCH_LEAGUES_REJECTED';
export const FETCH_LEAGUES_FULFILLED = 'FETCH_LEAGUES_FULFILLED';
export const FETCH_SEASONS = 'FETCH_SEASONS';
export const FETCH_SEASONS_PENDING = 'FETCH_SEASONS_PENDING';
export const FETCH_SEASONS_REJECTED = 'FETCH_SEASONS_REJECTED';
export const FETCH_SEASONS_FULFILLED = 'FETCH_SEASONS_FULFILLED';






