export const FETCH_LEAGUES = 'FETCH_LEAGUES';
export const FETCH_LEAGUES_PENDING = 'FETCH_LEAGUES_PENDING';
export const FETCH_LEAGUES_REJECTED = 'FETCH_LEAGUES_REJECTED';
export const FETCH_LEAGUES_FULFILLED = 'FETCH_LEAGUES_FULFILLED';
export const FETCH_SEASONS = 'FETCH_SEASONS';
export const FETCH_SEASONS_PENDING = 'FETCH_SEASONS_PENDING';
export const FETCH_SEASONS_REJECTED = 'FETCH_SEASONS_REJECTED';
export const FETCH_SEASONS_FULFILLED = 'FETCH_SEASONS_FULFILLED';
export const FETCH_ROUNDS = 'FETCH_ROUNDS';
export const FETCH_ROUNDS_PENDING = 'FETCH_ROUNDS_PENDING';
export const FETCH_ROUNDS_REJECTED = 'FETCH_ROUNDS_REJECTED';
export const FETCH_ROUNDS_FULFILLED = 'FETCH_ROUNDS_FULFILLED';
export const FETCH_MATCHES = 'FETCH_MATCHES';
export const FETCH_MATCHES_PENDING = 'FETCH_MATCHES_PENDING';
export const FETCH_MATCHES_REJECTED = 'FETCH_MATCHES_REJECTED';
export const FETCH_MATCHES_FULFILLED = 'FETCH_MATCHES_FULFILLED';





